server:
  port: 8080
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Routing Configuration
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: history-service
          uri: lb://history-service
          predicates:
            - Path=/api/history/**

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
